project:
  type: website
  output-dir: docs
  
website:
  title: "OUR CV WEBSITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CMHernandez.qmd
      - ESilao.qmd
      - FQuibranto.qmd
      - GBBumilao.qmd
      - LLegaspi.qmd
      - RJSebastian.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/ClammyZ/ProfEd7Website
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2023, Emmanuel Silao"

format:
  html:
    theme: cerulean
    toc: true

editor: source

